# Generated by rush/cli/scripts/bump-homebrew.sh — do not edit by hand.
class Rush < Formula
  desc "Agent execution engine for Rush agents"
  homepage "https://getrush.ai"
  version "0.2.23"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://cdn.getrush.ai/releases/rush-cli/0.2.23/rush-darwin-arm64"
      sha256 "9c23eec31cf34dda963e787c982ffa93f73a2135674e14b0f541ff04e0e1f5a0"
    end
    on_intel do
      url "https://cdn.getrush.ai/releases/rush-cli/0.2.23/rush-darwin-x64"
      sha256 "f565805274178b3ed75c9bccc24b3e967efdae8dd4c35d7cc9a154ca8dd83780"
    end
  end

  on_linux do
    on_arm do
      url "https://cdn.getrush.ai/releases/rush-cli/0.2.23/rush-linux-arm64"
      sha256 "5183f625e6712ac17f45a8fd5ad9b52b28b60bee33a1c454641554ce7d064123"
    end
    on_intel do
      url "https://cdn.getrush.ai/releases/rush-cli/0.2.23/rush-linux-x64"
      sha256 "e2adda8b49ba6a5d70d714b63ec9be8fe000e75569d4f6d7846926143ee75e77"
    end
  end

  def install
    bin.install Dir["*"].first => "rush"
    bin.install_symlink "rush" => "rushx"
  end

  def caveats
    <<~CAVEATS
      If you previously installed rush via the curl script, remove that copy
      so Homebrew's wins:
        rm -f ~/.rush/bin/rush ~/.rush/bin/rushx
      Upgrades are managed by Homebrew: brew upgrade rush
    CAVEATS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rush --version")
  end
end
