# Generated by rush/cli/scripts/bump-homebrew.sh — do not edit by hand.
class Rush < Formula
  desc "Agent execution engine for Rush agents"
  homepage "https://getrush.ai"
  version "0.2.54"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://cdn.getrush.ai/releases/rush-cli/0.2.54/rush-darwin-arm64"
      sha256 "9980babf463d0bb2e90a75daaf4d99b09520d7abbb8b1eafedafbfef61ca8128"
    end
    on_intel do
      url "https://cdn.getrush.ai/releases/rush-cli/0.2.54/rush-darwin-x64"
      sha256 "fed3208bd9081dc557aaf20b2833c388e2c09a4f304421ca7327c2aae377aaa7"
    end
  end

  on_linux do
    on_arm do
      url "https://cdn.getrush.ai/releases/rush-cli/0.2.54/rush-linux-arm64"
      sha256 "983c004abbead19a6bfc41e7c35867f100c02c450b85df16c47fbabdc6650a3b"
    end
    on_intel do
      url "https://cdn.getrush.ai/releases/rush-cli/0.2.54/rush-linux-x64"
      sha256 "ff6777625aaee4ceed8e69f44a6ec86a5ac060b68c15e20831c90063c08b02b7"
    end
  end

  def install
    bin.install Dir["*"].first => "rush"
    bin.install_symlink "rush" => "rushx"
  end

  def caveats
    <<~CAVEATS
      If you previously installed rush via the curl script, remove that copy
      so Homebrew's wins:
        rm -f ~/.rush/bin/rush ~/.rush/bin/rushx
      Upgrades are managed by Homebrew: brew upgrade rush
    CAVEATS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rush --version")
  end
end
