# Generated by rush/cli/scripts/bump-homebrew.sh — do not edit by hand.
class Rush < Formula
  desc "Agent execution engine for Rush agents"
  homepage "https://getrush.ai"
  version "0.2.19"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://cdn.getrush.ai/releases/rush-cli/0.2.19/rush-darwin-arm64"
      sha256 "309ddbe9496625da69c5c0663a331ea28d7241100403462d3186ed532f90d4b5"
    end
    on_intel do
      url "https://cdn.getrush.ai/releases/rush-cli/0.2.19/rush-darwin-x64"
      sha256 "ac48d1558b9beabd04fbcb9e7d10b4e735adac28c671435cb0f1468027dec595"
    end
  end

  on_linux do
    on_arm do
      url "https://cdn.getrush.ai/releases/rush-cli/0.2.19/rush-linux-arm64"
      sha256 "93cb71f54af66c65ddcfea9db4c64d46987297cfce5ac444e7304bdcdbdaaf2a"
    end
    on_intel do
      url "https://cdn.getrush.ai/releases/rush-cli/0.2.19/rush-linux-x64"
      sha256 "c58ac1e649ae0acba3507e6cd12a55d91bc819e34d24e1d2b864afa3f4a6e6f5"
    end
  end

  def install
    bin.install Dir["*"].first => "rush"
    bin.install_symlink "rush" => "rushx"
  end

  def caveats
    <<~CAVEATS
      If you previously installed rush via the curl script, remove that copy
      so Homebrew's wins:
        rm -f ~/.rush/bin/rush ~/.rush/bin/rushx
      Upgrades are managed by Homebrew: brew upgrade rush
    CAVEATS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rush --version")
  end
end
